import test from 'node:test';
import assert from 'node:assert/strict';
import {SDJ_PLANS,SDJ_PRODUCT,getSDJPlan,getPaidSDJPlan,sdjOrderKey} from '../lib/sdj.js';
import {SDJ_ACCOUNT,SDJ_SUCCESS_URL,inspectPremiumLink,premiumAvailability,prepareSDJPayment,paidSessionIntent} from '../lib/sdj-server.js';
import {recoveryToken,readRecoveryToken} from '../lib/sdj-recovery.js';
const linkId='plink_fixture';
const pi=(plan='premium')=>({id:'pi_fixture',livemode:true,status:'succeeded',amount:SDJ_PLANS[plan].amount,amount_received:SDJ_PLANS[plan].amount,currency:'jpy',metadata:{product:SDJ_PRODUCT,plan}});
const link=()=>({id:linkId,livemode:true,active:true,url:'https://buy.stripe.com/fixture',metadata:{product:SDJ_PRODUCT,plan:'premium'},payment_intent_data:{metadata:{product:SDJ_PRODUCT,plan:'premium'}},restrictions:{completed_sessions:{limit:10,count:0}},line_items:{has_more:false,data:[{quantity:1,price:{unit_amount:39800,currency:'jpy',tax_behavior:'inclusive',recurring:null}}]},after_completion:{type:'redirect',redirect:{url:SDJ_SUCCESS_URL+'?session_id={CHECKOUT_SESSION_ID}'}}});
const input={plan:'basic',customerName:'Sample Buyer',email:'buyer@example.invalid',requestId:'00000000-0000-4000-8000-000000000001'};
function stripe({payment=pi(),paymentLink=link(),session,account=SDJ_ACCOUNT}={}){
 const calls=[];
 return {calls,accounts:{retrieve:async()=>({id:account})},paymentLinks:{retrieve:async(id,params)=>{calls.push(['link',id,params]);return paymentLink;}},paymentIntents:{retrieve:async()=>payment,create:async(data,options)=>{calls.push(['create',data,options]);return {id:'pi_fixture',client_secret:'pi_fixture_secret_fake'};}},checkout:{sessions:{retrieve:async()=>session}}};
}
function session(payment=pi()){return {id:'cs_live_fixture',livemode:true,payment_link:linkId,mode:'payment',status:'complete',payment_status:'paid',currency:'jpy',amount_total:39800,metadata:{product:SDJ_PRODUCT,plan:'premium'},payment_intent:payment};}

test('exact approved prices and benefits',()=>{assert.equal(SDJ_PLANS.basic.amount,14900);assert.equal(SDJ_PLANS.basic.hasSession,false);assert.equal(SDJ_PLANS.premium.amount,39800);assert.equal(SDJ_PLANS.premium.hasSession,true);});
for(const bad of [undefined,null,'','BASIC','__proto__','constructor',[],{},'trial'])test(`reject unknown plan ${JSON.stringify(bad)}`,()=>assert.equal(getSDJPlan(bad),null));
test('new BASIC and PREMIUM payments give exact plan access',()=>{assert.equal(getPaidSDJPlan(pi('basic')).id,'basic');assert.equal(getPaidSDJPlan(pi()).id,'premium');});
test('legacy 39800 orders retain PREMIUM session entitlement',()=>{const p=pi();delete p.metadata.plan;assert.equal(getPaidSDJPlan(p).id,'premium');});
test('14900 does not get legacy PREMIUM entitlement',()=>{const p=pi('basic');delete p.metadata.plan;assert.equal(getPaidSDJPlan(p),null);});
for(const mutation of [{status:'processing'},{status:'requires_payment_method'},{amount:1},{amount_received:0},{currency:'usd'},{livemode:false},{metadata:{product:'other',plan:'premium'}},{metadata:{product:SDJ_PRODUCT,plan:'bad'}},{metadata:{product:SDJ_PRODUCT,plan:'basic'}}])test(`deny invalid paid claim ${JSON.stringify(mutation)}`,()=>assert.equal(getPaidSDJPlan({...pi(),...mutation}),null));
test('different plans have distinct browser order keys',()=>assert.notEqual(sdjOrderKey('basic','a@b.c','A'),sdjOrderKey('premium','a@b.c','A')));
test('nine completions available; ten or more sold out',()=>{for(const count of [0,9,10,11]){const l=link();l.restrictions.completed_sessions.count=count;assert.equal(inspectPremiumLink(l).status,count<10?'available':'sold_out');}});
test('manual deactivation with no sales is unavailable, not sold out',()=>{const l=link();l.active=false;assert.equal(inspectPremiumLink(l).status,'unavailable');});
for(const mutate of [l=>l.livemode=false,l=>l.restrictions.completed_sessions.limit=11,l=>delete l.restrictions.completed_sessions.count,l=>l.line_items.data[0].price.unit_amount=14900,l=>l.line_items.data[0].price.tax_behavior='exclusive',l=>l.line_items.data[0].quantity=2,l=>l.line_items.has_more=true,l=>l.payment_intent_data.metadata.plan='basic',l=>l.metadata.product='other',l=>l.url='https://evil.example.invalid',l=>l.allow_promotion_codes=true,l=>l.shipping_options=[{shipping_rate:'shr_fake'}],l=>l.automatic_tax={enabled:true},l=>l.payment_intent_data.capture_method='manual',l=>l.after_completion.redirect.url='https://evil.example.invalid'])test('misconfigured cap/link fails closed: '+mutate.toString(),()=>{const l=link();mutate(l);assert.throws(()=>inspectPremiumLink(l));});
test('missing PaymentLink configuration fails closed',async()=>{const s=stripe();await assert.rejects(premiumAvailability(s,''));assert.equal(s.calls.length,0);});
test('BASIC can start without PREMIUM configuration and amount from client is ignored',async()=>{const s=stripe();const r=await prepareSDJPayment(s,{...input,amount:1},null,'');assert.equal(r.plan,'basic');const c=s.calls.find(c=>c[0]==='create');assert.equal(c[1].amount,14900);assert.equal(c[1].metadata.plan,'basic');assert.deepEqual(c[1].allowed_payment_method_types,['card']);assert.match(c[2].idempotencyKey,/sdj-v2-basic-/);});
test('PREMIUM never creates a direct PaymentIntent',async()=>{const s=stripe();const r=await prepareSDJPayment(s,{plan:'premium'},null,linkId);assert.equal(r.url,link().url);assert.equal(s.calls.filter(c=>c[0]==='create').length,0);});
test('direct PREMIUM API rejected when sold out',async()=>{const l=link();l.restrictions.completed_sessions.count=10;const s=stripe({paymentLink:l});await assert.rejects(prepareSDJPayment(s,{plan:'premium'},null,linkId),e=>e.code==='sold_out'&&e.status===409);assert.equal(s.calls.filter(c=>c[0]==='create').length,0);});
test('old clients without plan cannot mint uncapped intents',async()=>{const s=stripe();await assert.rejects(prepareSDJPayment(s,{...input,plan:undefined},null,linkId),e=>e.code==='invalid_plan');assert.equal(s.calls.length,0);});
test('invalid BASIC customer cannot mint PaymentIntent',async()=>{const s=stripe();await assert.rejects(prepareSDJPayment(s,{...input,email:'bad'},null,linkId),e=>e.code==='invalid_customer');assert.equal(s.calls.length,0);});
test('wrong Stripe account fails closed',async()=>{const s=stripe({account:'acct_wrong'});await assert.rejects(prepareSDJPayment(s,input,null,linkId));assert.equal(s.calls.length,0);});
test('paid buyer resumes guide without another charge',async()=>{const s=stripe();const r=await prepareSDJPayment(s,input,'pi_existing',linkId);assert.deepEqual(r,{paid:true});assert.equal(s.calls.length,0);});
test('many concurrent requests only read the SAME bounded link; no custom intents',async()=>{const s=stripe();const r=await Promise.all(Array.from({length:25},()=>prepareSDJPayment(s,{plan:'premium'},null,linkId)));assert.equal(new Set(r.map(x=>x.url)).size,1);assert.ok(s.calls.every(x=>x[0]==='link'&&x[1]===linkId));});
test('valid PREMIUM session resolves paid intent',async()=>{const s=stripe({session:session()});assert.equal((await paidSessionIntent(s,'cs_live_fixture',linkId)).id,'pi_fixture');});
for(const change of [{payment_link:'plink_other'},{livemode:false},{amount_total:14900},{mode:'subscription'},{currency:'usd'},{metadata:{product:SDJ_PRODUCT,plan:'basic'}},{payment_intent:pi('basic')}])test('forged or unrelated session denied: '+JSON.stringify(change),async()=>{const s=stripe({session:{...session(),...change}});await assert.rejects(paidSessionIntent(s,'cs_live_fixture',linkId));});
test('completed but unpaid session does not grant course access',async()=>{const s=stripe({session:{...session(),payment_status:'unpaid'}});const p=await paidSessionIntent(s,'cs_live_fixture',linkId);assert.equal(p.status,'processing');assert.equal(getPaidSDJPlan(p),null);});
test('test session identifiers cannot access live premium guide',async()=>{await assert.rejects(paidSessionIntent(stripe(),'cs_test_fixture',linkId));});
test('recovery cookie signature and expiry preserved',()=>{const now=1700000000000;const token=recoveryToken('pi_fixture','mock-only-key',now);assert.equal(readRecoveryToken(token,'mock-only-key',now),'pi_fixture');assert.equal(readRecoveryToken(token,'wrong-key',now),null);assert.equal(readRecoveryToken(token,'mock-only-key',now+91*86400000),null);});
